---
- name: Make sure docker container storage exists
  ansible.builtin.file:
    path: "{{ docker_storage_mount_point }}"
    state: directory
    mode: '0755'

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
    driver: overlay
  loop: "{{ deploy_containers_networks }}"
