---
- name: Make sure server has iptables package
  ansible.builtin.apt:
    name: iptables
    state: present
    update_cache: true
  become: true

- name: Install wireguard package
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
  become: true
